### ISSUE TITLE
model.jason error

### ISSUE THREAD

**Issue by Agent259** [ardamavi/Game-Bot#15]
(base) C:\Users\Naga Ravi\Downloads\Game-Bot-master\Game-Bot-master>python ai.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "ai.py", line 58, in <module>
    main()
  File "ai.py", line 14, in main
    model_file = open('Data/Model/model.json', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Model/model.json'

**Comment by ardamavi** [comment]
Firstly you must train your AI Model.
