### ISSUE TITLE
Ive got this program 'working' to some extent... but I need some clarification

### ISSUE THREAD

**Issue by caretbay47** [ardamavi/Game-Bot#19]
So Ive gone through most of the code for this and I've fixed it to the point where i can actually run create_dataset.py without program breaking errors... However when I close the program there is only one 'img.jpg' is this how it is supposed to be or should there be a crap load of them?

**Comment by ardamavi** [comment]
If you can share your codes (as Pull Request), I can debug.

**Comment by caretbay47** [comment]
No ik whats wrong with it... i just need to know, when is the program supposed to take screenshots... and what format should the images be in?... like np.float32 or np.float64 uint8 jpg ect... and the whole numpy array thing... whats the difference between save_img and screenshot() why do u need both of those

**Comment by ardamavi** [comment]
The screenshot is taken when you make a move (for example, when you press the key).
`save_img`: Saves screenshots
`screenshot`: Takes screenshots
